---
title: "NOAA Data"
---

The dataset we used is the NOAA. It contains five core variables for all New York state weather stations from January 1, 1981 through December 31, 2010. We will focus on data from January 1,2016 to December 31, 2016. 
The resulting R dataset weather contains variables:
name: Name of weather station
id: Weather station ID
date: Date of observation
prcp: Precipitation (tenths of mm)
tmax: Maximum temperature (tenths of degrees C)
tmin: Minimum temperature (tenths of degrees C)

### Problem 1 
In this problem we have 3 plots. That is a scatter plot, a box plot and a bar plot. The scatter plot illustrates the relationship between tmax and tmin. The box plot compares the difference of precipitation between stations. The bar plot illustrate the mean of tmax across each months for each station.

The dashboard containing our solution to this problem is [here](dashboard.html).

### Problem 2
We use selectInput widgets to choose three different areas and we also use sliderInput widget to choose the precipitation. And then we draw interactive scatterplot interactive box plot and interactive barchart based on problem 1. We can run the shiny codes the first time [here](http://127.0.0.1:7335/shiny_dashboard.Rmd)，and here is the [repo of rmd file](https://github.com/zxinxinz/P8105_hw6_shiny)

### GitHub repo(s)
The Git repo containing the solution to this Problem 1 is [here](https://github.com/zxinxinz/P8105_hw6-dashboard).

The Git repo containing the solution to this Problem 2 is [here](https://github.com/zxinxinz/P8105_hw6_shiny)

The Git repo containing the solution to the website is [here](https://github.com/zxinxinz/website)




